mybatis-plus:
  configuration:
    # 关闭驼峰转换
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      # 不为 null 才进行更新
      update-strategy: not_null

server:
  port: 8080
  servlet:
    session:
      timeout: 120m
      cookie:
        max-age: 120m
spring:
  profiles:
    active: dev
    include: self
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB