mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
    global-config:
        db-config:
            logic-delete-field: deleted
            logic-delete-value: 1
            logic-not-delete-value: 0
            update-strategy: not_null

server:
    port: 8080
    servlet:
        session:
            timeout: 120m
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: wajing
        url: jdbc:mysql://10.1.252.45:3306/mam?serverTimezone=UTC
        username: root
    redis:
        host: 10.1.252.45
        password: asdfgh
        port: 6379
    security:
        user:
            name: javaboy
            password: 123
    elasticsearch:
        rest:
            uris: 10.1.252.45:9200
            password: wajing
    profiles:
        active: prod
        include: self
    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB