videoStoredPath: E:/Video/target/video/
imageStoredPath: E:/Video/target/images/
serverPath: http://192.168.111.128/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: wajing
    url: jdbc:mysql://localhost:3306/mam?serverTimezone=UTC
    username: root
  redis:
    host: 192.168.111.128
    password: asdfgh
    port: 6379
  security:
    user:
      name: javaboy
      password: 123
  elasticsearch:
    rest:
      uris: 192.168.111.128:9200
      password: wajing
      username: elastic
mybatis-plus:
  configuration:
    # 控制打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl